"""Write or remove the gitignored compile-time product overlay.

Stdout is machine-readable ``KEY=value`` lines for ``compiler.bat``.
Diagnostics go to stderr via logging.
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path

log = logging.getLogger(__name__)

_TRUE_VALUES = {"1", "true", "yes", "on"}
_FALSE_VALUES = {"0", "false", "no", "off"}
# cmd's `for /f` leaves an undefined token unexpanded, so `APP_FLAVOR=` would assign
# the literal string "%B". Every emitted key must carry a non-empty value.
NO_FLAVOR_SENTINEL = "none"
_OVERLAY_TEMPLATE = (
    '"""Auto-generated by write_product_overlay.py. Do not commit."""\n'
    "\n"
    "FEATURE_THRIVE: bool = {thrive!r}\n"
    "FEATURE_SESSION_REPORT: bool = {session_report!r}\n"
)


def default_overlay_path() -> Path:
    """Return the overlay path next to ``wiibble.product``."""
    return (
        Path(__file__).resolve().parent.parent / "src" / "wiibble" / "_product_build.py"
    )


def parse_env_bool(name: str, raw: str | None) -> bool | None:
    """Parse a feature env var as True, False, or unset.

    Args:
        name: Environment variable name (for error messages).
        raw: Raw env value, or None when the variable is absent.

    Returns:
        Parsed boolean, or None when the variable is unset or blank.

    Raises:
        ValueError: If the value is set but not a recognised boolean token.
    """
    if raw is None or not raw.strip():
        return None
    token = raw.strip().lower()
    if token in _TRUE_VALUES:
        return True
    if token in _FALSE_VALUES:
        return False
    raise ValueError(f"{name} must be 0/1/true/false/yes/no/on/off, got {raw!r}")


def resolve_product_features(
    profile: str | None = None,
    thrive_override: bool | None = None,
    session_report_override: bool | None = None,
) -> tuple[bool, bool]:
    """Resolve Thrive and session-report flags from profile and overrides.

    Args:
        profile: ``full`` or ``lite``. None reads ``WIIBBLE_PROFILE`` (default full).
        thrive_override: Explicit Thrive flag. None reads ``WIIBBLE_FEATURE_THRIVE``.
        session_report_override: Explicit report flag. None reads
            ``WIIBBLE_FEATURE_SESSION_REPORT``.

    Returns:
        ``(feature_thrive, feature_session_report)``.

    Raises:
        ValueError: If the profile or an override token is invalid.
    """
    resolved_profile = (
        profile
        if profile is not None
        else (os.environ.get("WIIBBLE_PROFILE") or "full")
    ).strip().lower()
    if resolved_profile == "lite":
        thrive, session_report = False, False
    elif resolved_profile == "full":
        thrive, session_report = True, True
    else:
        raise ValueError(
            f"WIIBBLE_PROFILE must be 'full' or 'lite', got {resolved_profile!r}"
        )

    if thrive_override is None:
        thrive_override = parse_env_bool(
            "WIIBBLE_FEATURE_THRIVE", os.environ.get("WIIBBLE_FEATURE_THRIVE")
        )
    if session_report_override is None:
        session_report_override = parse_env_bool(
            "WIIBBLE_FEATURE_SESSION_REPORT",
            os.environ.get("WIIBBLE_FEATURE_SESSION_REPORT"),
        )
    if thrive_override is not None:
        thrive = thrive_override
    if session_report_override is not None:
        session_report = session_report_override
    return thrive, session_report


def app_flavor_suffix(thrive: bool, session_report: bool) -> str:
    """Return the installer filename flavor, or empty for the full product.

    Args:
        thrive: Whether Thrive is compiled in.
        session_report: Whether in-app session reports are compiled in.

    Returns:
        ``lite``, ``no-thrive``, ``no-reports``, or ``""`` for the full build.
    """
    if thrive and session_report:
        return ""
    if not thrive and not session_report:
        return "lite"
    if not thrive:
        return "no-thrive"
    return "no-reports"


def write_product_overlay(
    thrive: bool,
    session_report: bool,
    overlay_path: Path | None = None,
) -> Path | None:
    """Write or delete the overlay so defaults stay True when both features are on.

    Args:
        thrive: Thrive compile-time flag.
        session_report: Session-report compile-time flag.
        overlay_path: Overlay file to write. Defaults to ``src/wiibble/_product_build.py``.

    Returns:
        Path written, or None when the overlay was removed because both flags are True.
    """
    path = overlay_path if overlay_path is not None else default_overlay_path()
    if thrive and session_report:
        delete_product_overlay(path)
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        _OVERLAY_TEMPLATE.format(thrive=thrive, session_report=session_report),
        encoding="utf-8",
    )
    log.info("Wrote product overlay %s", path)
    return path


def delete_product_overlay(overlay_path: Path | None = None) -> None:
    """Remove the generated overlay if it exists.

    Args:
        overlay_path: Overlay file to delete. Defaults to ``src/wiibble/_product_build.py``.
    """
    path = overlay_path if overlay_path is not None else default_overlay_path()
    if path.is_file():
        path.unlink()
        log.info("Removed product overlay %s", path)


def emit_compiler_flags(thrive: bool, session_report: bool) -> None:
    """Write ``KEY=value`` lines for ``compiler.bat`` to parse.

    The full build has no flavor suffix, emitted as ``NO_FLAVOR_SENTINEL`` because
    ``compiler.bat`` cannot parse an empty value.

    Args:
        thrive: Thrive compile-time flag.
        session_report: Session-report compile-time flag.
    """
    flavor = app_flavor_suffix(thrive, session_report) or NO_FLAVOR_SENTINEL
    sys.stdout.write(f"THRIVE={int(thrive)}\n")
    sys.stdout.write(f"SESSION_REPORT={int(session_report)}\n")
    sys.stdout.write(f"APP_FLAVOR={flavor}\n")


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse CLI arguments for the overlay writer.

    Args:
        argv: Argument list excluding the program name. None uses ``sys.argv``.

    Returns:
        Parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description="Write the gitignored WIIBBLE product overlay for Nuitka builds."
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete the overlay and exit without writing flags.",
    )
    parser.add_argument(
        "--overlay-path",
        type=Path,
        default=None,
        help="Override overlay path (tests).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Write or clean the overlay and emit compiler flags.

    Args:
        argv: Argument list excluding the program name.

    Returns:
        Process exit code (0 on success, 1 on invalid configuration).
    """
    logging.basicConfig(
        level=logging.INFO,
        stream=sys.stderr,
        format="[product] %(message)s",
    )
    args = _parse_args(argv)
    overlay_path = args.overlay_path
    if args.clean:
        delete_product_overlay(overlay_path)
        return 0
    try:
        thrive, session_report = resolve_product_features()
    except ValueError as exc:
        log.error("%s", exc)
        return 1
    write_product_overlay(thrive, session_report, overlay_path)
    emit_compiler_flags(thrive, session_report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
